coverage:
  status:
    project:
      JETLS.jl:
        flags: [JETLS.jl]
        informational: true
      HierarchicalTestSets.jl:
        flags: [HierarchicalTestSets.jl]
        informational: true
      LSP.jl:
        flags: [LSP.jl]
        informational: true
      MarkdownSource.jl:
        flags: [MarkdownSource.jl]
        informational: true
      TOMLSource.jl:
        flags: [TOMLSource.jl]
        informational: true
    patch:
      default:
        informational: true

flag_management:
  default_rules:
    carryforward: true
