name = "TrimAnalyzer"
uuid = "db0f0d6f-36c4-4e19-a1b7-72446e3087f7"
version = "0.1.0"
authors = ["Shuhei Kadowaki <aviatesk@gmail.com>"]

[deps]
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
LSP = "880dcf91-6fde-4251-87fc-bfd84012291a"

[sources]
JET = {rev = "master", url = "https://github.com/aviatesk/JET.jl"}
LSP = {path = "/Users/aviatesk/julia/packages/JETLS/LSP"}

[compat]
InteractiveUtils = "1.11.0"
JET = "0.10.6"
JSON3 = "1.14.3"
LSP = "0.1"

[apps.report-trim]
