name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false # don't stop CI even when one of them fails
      matrix:
        include:
          # - version: "1" # current stable
          #   os: ubuntu-latest
          #   arch: x64
          - version: "1.12" # minimum version supported
            os: ubuntu-latest
            arch: x64
          - version: "1.13-nightly" # next release
            os: ubuntu-latest
            arch: x64
          - version: "nightly" # dev
            os: ubuntu-latest
            arch: x64
          # - version: "1" # x86 ubuntu
          #   os: ubuntu-latest
          #   arch: x86
          # - version: "1" # x86 windows
          #   os: windows-latest
          #   arch: x86
          # - version: "1" # x64 windows
          #   os: windows-latest
          #   arch: x64
          # - version: "1" # x64 macOS
          #   os: macos-latest
          #   arch: x64
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/cache@v2
      - name: set LocalPreferences.toml
        working-directory: .
        run: |
          echo '
          [JET]
          JET_DEV_MODE = true # allow JET to be loaded on nightly
          ' > LocalPreferences.toml
      - uses: julia-actions/julia-buildpkg@latest
      - uses: julia-actions/julia-runtest@latest
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v5

  JETLS_DEV_MODE:
    name: Test with `JETLS_DEV_MODE = true`
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: "1.12" # most stable version
          arch: x64
      - uses: julia-actions/cache@v2
      - name: set LocalPreferences.toml
        working-directory: .
        run: |
          echo '
          [JETLS]
          JETLS_DEV_MODE = true

          [JET]
          JET_DEV_MODE = true # allow JET to be loaded on nightly
          ' > LocalPreferences.toml
      - uses: julia-actions/julia-buildpkg@latest
      - uses: julia-actions/julia-runtest@latest
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v5

  JETLS_DEBUG_LOWERING:
    name: Test with `JETLS_DEBUG_LOWERING = true`
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: "1.12" # most stable version
          arch: x64
      - uses: julia-actions/cache@v2
      - name: set LocalPreferences.toml
        working-directory: .
        run: |
          echo '
          [JETLS]
          JETLS_DEBUG_LOWERING = true

          [JET] # allow JET to be loaded on nightly
          JET_DEV_MODE = true
          ' > LocalPreferences.toml
      - uses: julia-actions/julia-buildpkg@latest
      - uses: julia-actions/julia-runtest@latest
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v5

  JULIA_NUM_THREADS:
    name: Test with `JULIA_NUM_THREADS = 4,2`
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: "1.12" # most stable version
          arch: x64
      - uses: julia-actions/cache@v2
      - name: set LocalPreferences.toml
        working-directory: .
        run: |
          echo '
          [JET] # allow JET to be loaded on nightly
          JET_DEV_MODE = true
          ' > LocalPreferences.toml
      - uses: julia-actions/julia-buildpkg@latest
      - uses: julia-actions/julia-runtest@latest
        env:
          JULIA_NUM_THREADS: "4,2"
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v5

  test_runserver:
    name: Test runserver.jl
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: "1.12" # most stable version
          arch: x64
      - uses: julia-actions/julia-buildpkg@latest
      - name: run test
        run: |
          julia --startup-file=no --project=./test ./test/test_runserver.jl
